[build]
  publish = "dist"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://blinders-secure-chat-backend.onrender.com/api"
  VITE_SOCKET_URL = "https://blinders-secure-chat-backend.onrender.com"

[context.deploy-preview.environment]
  VITE_API_URL = "https://blinders-secure-chat-backend.onrender.com/api"
  VITE_SOCKET_URL = "https://blinders-secure-chat-backend.onrender.com"
